DROP TABLE IF EXISTS matches;

CREATE TABLE matches (
  id SERIAL PRIMARY KEY NOT NULL,
  user_one INTEGER REFERENCES users(id) ON DELETE CASCADE,
  user_two INTEGER REFERENCES users(id) ON DELETE CASCADE DEFAULT NULL,
  reciprocated BOOLEAN DEFAULT FALSE
);
